### ISSUE TITLE
Share your work with Mattermost community?

### ISSUE THREAD

**Issue by hannaparks** [mharrend/matterbot-calendarBot#1]
Hi Marco, 

We came across your work and we'd love to help share it with the Mattermost community.

If this might be interesting for you, we wondered if you'd help complete a form to tell us more about your work so we can promote it? 

Here's the form: 
https://spinpunch.wufoo.com/forms/mattermost-integrations-and-installers/

**Comment by mharrend** [comment]
@hannapark84 I have completed the form provided by you.

**Comment by it33** [comment]
Thanks @mharrend, 

We're preparing a tweet to go out, if you'd like to meet some other integration developers, we'd welcome you to [join our Mattermost Integrations channel](https://pre-release.mattermost.com/core/channels/integrations) 

We're working on a banner to let people know about your work: 

![image](https://cloud.githubusercontent.com/assets/177788/16895341/31b154b8-4b28-11e6-8a1b-13f578472094.png)
